[profile.default]
src = "contracts"
out = "out"
libs = [
    "lib",
    "node_modules",
]
test = "test"
script = "script"

# Compiler settings
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

# Additional settings
fs_permissions = [{ access = "read-write", path = "./" }]
gas_reports = ["*"]

# RPC endpoints for different networks
[rpc_endpoints]
bsc = "https://bsc-dataseed.binance.org/"
bsc_testnet = "https://data-seed-prebsc-1-s1.binance.org:8545/"
localhost = "http://127.0.0.1:8545"

# Etherscan API keys for contract verification
[etherscan]
bsc = { key = "${BSC_API_KEY}", url = "https://api.bscscan.com/api" }
bsc_testnet = { key = "${BSC_API_KEY}", url = "https://api-testnet.bscscan.com/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
